### ISSUE TITLE
RCTBridgeModule.h not found when trying to build

### ISSUE THREAD

**Issue by steventnorris-40AU** [oblador/react-native-keychain#126] opened 2018-03-30 20:37 UTC
When attempting to build and run for ios, the below error is recieved. I have attempted both react-native link and manually linking the node module. The error persists. Without the keychain dependency, there are no issues and the applications functions as expected.

```
In file included from [REDACTED]/node_modules/react-native-keychain/RNKeychainManager/RNKeychainManager.m:10:
[REDACTED]/node_modules/react-native-keychain/RNKeychainManager/RNKeychainManager.h:9:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import "React/RCTBridgeModule.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **


The following build commands failed:
        CompileC [REDACTED]/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNKeychain.build/Objects-normal/x86_64/RNKeychainManager.o [REDACTED]/node_modules/react-native-keychain/RNKeychainManager/RNKeychainManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by steventnorris-40AU** [comment] 2018-03-30 20:39
```
"react-native": "0.52.1",
"react-native-keychain": "^3.0.0-rc.3",
```

**Comment by vonovak** [comment] 2018-03-30 20:58
do you use pods? if so, please follow manual instructions and make sure that react-native-keychain is not in you podfile

**Comment by steventnorris-40AU** [comment] 2018-03-30 21:01
I don't use anything that isn't installed via npm at this point. No manually added dependencies.

**Comment by steventnorris-40AU** [comment] 2018-04-04 16:10
Any info on this? When I build from React Native with react sim I also get this:

`TypeError: undefined is not an object (evaluating 'RNKeychainManager.getGenericPasswordForOptions')`

I dug into the code and it seems to be called from your library when I call `Keychain.getGenericPassword()`, which fires fine and enters your library before failing at that `getGenericPasswordForOptions` line.

**Comment by steventnorris-40AU** [comment] 2018-04-04 17:55
To give some more information, I uninstalled the keychain dependency entirely then reinstalled from scratch as follows;

1. added `react-native-keychain: "^3.0.0-rc.3" ` to package.json
2. npm install
3. react-native link react-native-keychain
4. react-native run-ios

No errors in build so far at this point. I then add this code:

```
import * as Keychain from 'react-native-keychain'
....
componentWillMount(){
    LoadingActions.showLoading()
    loginInfo = Keychain.getGenericPassword()
    if(loginInfo){
      API.login(loginInfo.username, loginInfo.password)
      .then(({response, success}) => {
        if(success){
          this.navigateToGo()
        }
        else{
          this.navigateToIntro()
        }
      })
      .catch((error) => {
        this.navigateToIntro()
      })
    }
    this.navigateToIntro()
  }

```
When code reaches the `Keychain.getGenericPassword() `line, it enters the code for your library and fails at `getGenericPasswordForOptions` with the below crash error:

`TypeError: Cannot read property 'getGenericPasswordForOptions' of undefined`

This library seems to be the most suggested library for using keychain with react native, but I haven't been able to get it to use even the most basic features yet.

**Comment by vonovak** [comment] 2018-04-04 20:46
Hi! Sorry to hear you have a problem.
First, you're not awaiting the result of the Keychain call. The second
problem is that the module probably is not linked correctly.

If you can't make it work, please create a minimal reproduction of your
problem as a github report and share it here. I'll try to take a look.

**Comment by steventnorris-40AU** [comment] 2018-04-04 20:54
My minimal reproduction is the above code. Following those steps for install and then using that code, I get the given error. I've moved on to a different library due to deadlines.

**Comment by vonovak** [comment] 2018-04-04 20:56
Hi, minimal reproduction is something I can open up in xcode and run for
myself, not a code snippet. Thanks.

**Comment by steventnorris-40AU** [comment] 2018-04-04 20:57
Completely understand. Not able to provide that at this time as I've had to move on to a different module.

**Comment by oblador** [comment] 2018-04-04 21:04
Hi, the problem is that you are trying to link this module with CocoaPods without also linking React Native with said dependency manager. `react-native link` will assumes that you want to use CocoaPods for all dependencies if you have a `Podfile` which in this case seems to be a faulty assumption but outside of our control. Sorry to hear that you chose a different library, it probably works due to not supporting CocoaPods. Closing as inactionable.

**Closed by oblador** 2018-04-04 21:04 UTC

**Comment by inturbidus** [comment] 2018-07-06 01:33
@steventnorris-40AU and for others coming here after having trouble with react-native-keychain.  
See my comment here https://github.com/itinance/react-native-fs/issues/408#issuecomment-402897855

After attempting several times to get this to install using the ignite-keychain plugin.  I came upon this error

```
In file included from [REDACTED]/node_modules/react-native-keychain/RNKeychainManager/RNKeychainManager.m:10:
[REDACTED]/node_modules/react-native-keychain/RNKeychainManager/RNKeychainManager.h:9:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import "React/RCTBridgeModule.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~

```
Your Podfile probably has a local link to the RNKeychainManager with a dependency on React (0.11 old version).  To fix, add this to your Podfile and run `pod install`:
```
# React Native requirements
pod 'yoga', path: './node_modules/react-native/ReactCommon/yoga'
pod 'DoubleConversion', :podspec => './node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'
pod 'GLog', :podspec => './node_modules/react-native/third-party-podspecs/GLog.podspec'
pod 'React', path: './node_modules/react-native', subspecs: [
  'Core',
  'jschelpers',
  'cxxreact',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTWebSocket',
]

```
I had to modify this slightly changing GLog to glog. Also, if your node_modules directory is not in the same directory as your Podfile change your paths to ../node_modules

**Comment by shawnventi** [comment] 2018-10-11 16:35
I was having the same problem that the **RCTBridgeModule.h** file could not be found while building, however, I am using Pods to support another module that I already had up and running. I just attempted @inturbidus solution to add the React Native requirements to my Podfile however now am faced with a new issue. 

The build now is successful however when attempting `react-native run-ios` the bundling process fails with the following error:
```
error: bundling failed: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: ~/App/ios/Pods/React/package.json collides with ~/App/node_modules/react-native/package.json
```

I'm slightly lost and would greatly appreciate any pointers!

**Comment by thehellmaker** [comment] 2019-10-15 19:46
did a pod update and all fell in place for me
