### ISSUE TITLE
error: package android.support.annotation does not exist

### ISSUE THREAD

**Issue by Xesme** [oblador/react-native-keychain#225] opened 2019-07-03 16:00 UTC
I am working on a project that is currently upgrading to RN v59/60.rc.3 I am trying to build on Android Studio (AndroidX) and I am running into this error. Has anyone else hit this recently? Using "react-native-keychain": "^3.1.3". Let me know if you need to see my gradle files. 

![image](https://user-images.githubusercontent.com/24839005/60606838-ed9e8e00-9d70-11e9-80ce-b1cd95cdf288.png)

**Comment by vonovak** [comment] 2019-07-03 20:29
closing as duplicate of #187

**Closed by vonovak** 2019-07-03 20:29 UTC
