### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNativeKeychain2.default.setGenericPassword')]

### ISSUE THREAD

**Issue by sganti564** [oblador/react-native-keychain#144] opened 2018-08-19 10:37 UTC
This issue happening in IOS. RN: 0.51.0, "react-native-keychain": "^3.0.0"
Tried all the manual settings mentioned in the Readme. 
Still no luck. Struggling with this from 2 days. any help is highly appreciated.

**Comment by LinusU** [comment] 2018-08-20 11:11
Hmm, it would, of course, be nice if it worked in 0.51, but that is a quite old version of React Native. Have you tried with version 0.56?

**Comment by rickgonzalez** [comment] 2018-08-25 16:27
As libraries for 56 are still evolving I'm staying at RN 55 for now.  I've tried every form of installation recommended, manual linking, re-built project from scratch, removed potential conflicts, no dice.  XCode shows that the library is being included in builds as it shows default warnings.  Still the problem remains - Cannot read property 'setGenericPasswordForOptions' of undefined.

As 3.0 was built for 5.6 are there backwards compatibility issues?

**Comment by tedscape** [comment] 2018-08-27 04:32
I am having this issue as well

**Comment by tedscape** [comment] 2018-08-28 01:02
After a day and half, the issue got resolved after I reset the whole project,  linked it manually. The automatic linking is broken and I would advise it being removed from documentation.

**Comment by LinusU** [comment] 2018-08-28 13:11
> The automatic linking is broken

If this is true we should absolutely fix this. This is also something that the React Native team wants to hear about so be sure to open an issue there.

Automatic linking is incredibly much more simpler for users, so I think we should recommend using that, and make sure that it works.

Manual linking is, I feel, more intended for people that embeds React Native in an already existing app...

**Comment by MayurBar** [comment] 2018-09-25 13:14
Still getting error after manually adding, do I also need to use CocoaPods?

**Comment by vonovak** [comment] 2018-10-30 00:43
closing this since it's hard to help without a reproduction. Sometimes the automatic linking fails because of podspec file: see the `NOTE` here https://github.com/react-native-community/react-native-google-signin/blob/master/ios-guide.md#automatic

**Closed by vonovak** 2018-10-30 00:43 UTC
