### ISSUE TITLE
TypeError: Cannot read property 'setGenericPasswordForOptions' of undefined

### ISSUE THREAD

**Issue by AGASampath** [oblador/react-native-keychain#147] opened 2018-09-12 11:05 UTC

**Comment by LinusU** [comment] 2018-09-12 11:18
Probably the same problem as #144?

**Comment by AGASampath** [comment] 2018-09-12 11:40
no

**Comment by LinusU** [comment] 2018-09-12 12:11
Why do you think that? 🤔

**Comment by vonovak** [comment] 2018-09-12 14:00
@AGASampath this indeed seems to be a duplicate of #144 - please make sure the module is linked correctly

**Closed by vonovak** 2018-09-12 14:00 UTC
