### ISSUE TITLE
Unusual Issue with rogue default value, anyone else encountered?

### ISSUE THREAD

**Issue by bnbon** [oblador/react-native-keychain#648] opened 2024-08-13 22:49 UTC
Hi, Using v8.2.0, with the latest version of react-native.

When I install the App on a new device, or if I reset the simulator, clean the build, and then build to simulator, when the credentials are fetched it has username of _pfo and a password value of 1.

If I reset the values, they go, but by default these are there.

Is there anything that could be setting these values, its extremely frustrating!

 LOG  {"password": "1", "service": "xxx.xxxx", "storage": "keychain", "username": "_pfo"}
 
 
 ````
   useEffect(() => {
    const loadCredentials = async () => {
      try {
        const credentials = await Keychain.getGenericPassword({
          authenticationPrompt: {
            title: 'Authentication required',
            subtitle: 'Log in to your account',
            description: 'Please authenticate to access your credentials',
            cancel: 'Cancel',
          },
        });
        console.log(credentials);
        if (credentials) {
          setEmail(credentials.username);
          setPassword(credentials.password);
        }
      } catch (error) {
        console.log('Keychain could not be accessed!');
      }
    };

    loadCredentials();
  }, []);
  ````
  
  
  and I store it this way.

````
      await Keychain.setGenericPassword(email, password, {
        accessible: Keychain.ACCESSIBLE.WHEN_UNLOCKED_THIS_DEVICE_ONLY,
        accessControl: Keychain.ACCESS_CONTROL.BIOMETRY_ANY,
      });
````

Any issues anyone can see, any clues where I could look? Its a head scratcher!

**Comment by DorianMazur** [comment] 2024-09-23 17:20
Hey @bnbon 

It looks like this issue is caused by a conflict with Firebase, as discussed in [this GitHub issue](https://github.com/oblador/react-native-keychain/issues/363). The recommended solution is to use a different service ID to avoid the collision.

Since this is a duplicate, I'll go ahead and close this issue.

**Closed by DorianMazur** 2024-09-23 17:20 UTC
