### ISSUE TITLE
 Could not resolve all artifacts for configuration ':react-native-keychain:classpath'.

### ISSUE THREAD

**Issue by zhengyanGit** [oblador/react-native-keychain#524] opened 2022-01-11 06:12 UTC
版本8.0.0 gradle-test-logger-plugin-2.0.0.pom这个依赖下载不下来，版本6.2.0 没这个问题

**Comment by oblador** [comment] 2022-06-23 12:14
Duplicate of https://github.com/oblador/react-native-keychain/issues/523

**Closed by oblador** 2022-06-23 12:14 UTC

**Comment by samiullah0243preesoft** [comment] 2022-07-03 09:28
you just need to do npx jetify

**Comment by teogomes** [comment] 2023-02-08 21:04
Try upgrading com.android.tools.build:gradle
